[tool.poetry]
name = "registration-test"
version = "0.1.0"
description = ""
authors = ["Savchenko Dmitriy"]
license = "GNU GPL v3"

[tool.poetry.dependencies]
python = "^3.9"
flask = "*"
requests = "*"
markupsafe = "*"
click = "*"
psycopg2 = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
